### ISSUE TITLE
Build is not working

### ISSUE THREAD

**Issue by maciejkorsan** [yuanqing/create-figma-plugin#2]
when I run `npm run build` I get webpack configuration error:

```
npm run build

> figma-hello-world@0.0.0 build /Users/korsanstudio/projekty/2019/figma/figma-hello-world
> create-figma-plugin build

(node:6756) UnhandledPromiseRejectionWarning: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry['ui'] should be a string.
      -> The string is resolved to a module which is loaded upon startup.
    * configuration.entry['ui'] should be an array:
      [non-empty string]
      -> A non-empty array of non-empty strings
    * configuration.entry['ui'] should be one of these:
      [non-empty string]
      -> All modules are loaded upon startup. The last one is exported.
    * configuration.entry['ui'] should be one of these:
      non-empty string | [non-empty string]
      -> An entry point with name
    at webpack (/Users/korsanstudio/projekty/2019/figma/figma-hello-world/node_modules/webpack/lib/webpack.js:31:9)
    at /Users/korsanstudio/projekty/2019/figma/figma-hello-world/node_modules/@create-figma-plugin/build/src/build-bundle.js:36:5
    at new Promise (<anonymous>)
    at buildBundle (/Users/korsanstudio/projekty/2019/figma/figma-hello-world/node_modules/@create-figma-plugin/build/src/build-bundle.js:35:10)
(node:6756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by maciejkorsan** [comment]
Ok, I've found that it's related to the `"ui"` property in `package.json` - for now it's required

**Comment by yuanqing** [comment]
Thanks @maciejkorsan for reporting this and trying this out! Will look into this

This tool is undergoing heavy development (haven’t really shared it publicly) – clearly still some bugs to iron out

**Comment by maciejkorsan** [comment]
sure - I understand ;) if you need help - let me know :)

**Comment by yuanqing** [comment]
As of `0.0.5`, building the plugin (with an optional `ui` field) should work
