### ISSUE TITLE
babel.config.js interference

### ISSUE THREAD

**Issue by reintroducing** [yuanqing/create-figma-plugin#30]
Hello,
I am building my figma plugin in a repo that has a few other "packages" in it. I have a root level custom `babel.config.js` file and this file is causing the Figma plugin to no longer build properly. Here is a sample (there are many more like this) of the errors:
```
> build-figma-plugin --watch

info Building plugin...
error Module build failed (from ./node_modules/babel-loader/lib/index.js):
error SyntaxError: /Users/mprzybylski/Work/fe-pulse/node_modules/@create-figma-plugin/ui/lib/components/button/button.js: pragma and pragmaFrag cannot be set when runtime is automatic.
error > 1 | /** @jsx h */
error     | ^
error   2 | import classnames from '@sindresorhus/class-names';
error   3 | import { h } from 'preact';
error   4 | import { useCallback } from 'preact/hooks';
error     at File.buildCodeFrameError (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/core/lib/transformation/file/file.js:240:12)
error     at NodePath.buildCodeFrameError (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/path/index.js:138:21)
error     at PluginPass.enter (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/plugin-transform-react-jsx/lib/create-plugin.js:163:28)
error     at newFn (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/visitors.js:175:21)
error     at NodePath._call (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/path/context.js:55:20)
error     at NodePath.call (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/path/context.js:42:17)
error     at NodePath.visit (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/path/context.js:92:31)
error     at TraversalContext.visitQueue (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/context.js:116:16)
error     at TraversalContext.visitSingle (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/context.js:85:19)
error     at TraversalContext.visit (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/context.js:144:19)
error
error Module build failed (from ./node_modules/babel-loader/lib/index.js):
error SyntaxError: /Users/mprzybylski/Work/fe-pulse/node_modules/@create-figma-plugin/ui/lib/components/checkbox/checkbox.js: pragma and pragmaFrag cannot be set when runtime is automatic.
error > 1 | /** @jsx h */
error     | ^
error   2 | import classnames from '@sindresorhus/class-names';
error   3 | import { h } from 'preact';
error   4 | import { useCallback } from 'preact/hooks';
error     at File.buildCodeFrameError (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/core/lib/transformation/file/file.js:240:12)
error     at NodePath.buildCodeFrameError (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/path/index.js:138:21)
error     at PluginPass.enter (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/plugin-transform-react-jsx/lib/create-plugin.js:163:28)
error     at newFn (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/visitors.js:175:21)
error     at NodePath._call (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/path/context.js:55:20)
error     at NodePath.call (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/path/context.js:42:17)
error     at NodePath.visit (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/path/context.js:92:31)
error     at TraversalContext.visitQueue (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/context.js:116:16)
error     at TraversalContext.visitSingle (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/context.js:85:19)
error     at TraversalContext.visit (/Users/mprzybylski/Work/fe-pulse/node_modules/@babel/traverse/lib/context.js:144:19)
error
```

If I rename the file to `_babel.config.js` (or just remove it), the build works fine, but I need this babel file for the other packages that are built in the repo.

Is there any way to avoid the figma plugin build using the babel file? I tried the following in the config file:
```js
exclude: ['./packages/figma'],
```
that didn't work, produces the same issues.

```js
ignore: ['./packages/figma'],
```
that also didn't work, produced the following:
```
> build-figma-plugin --watch

info Building plugin...
error Module parse failed: Unexpected token (56:8)
error File was processed with these loaders:
error  * ./node_modules/babel-loader/lib/index.js
error You may need an additional loader to handle the result of these loaders.
error |
error |     return (
error >         <Container space="medium">
error |             <VerticalSpace space="small" />
error |             <Text muted>Export design token JSON</Text>
info Watching...
```

Is there any way to get around this?

**Comment by reintroducing** [comment]
i ended up doing this, which seems to have fixed the issue (though I'm honestly not sure why):

```
"figma:start": "BABEL_ENV=figma build-figma-plugin --watch",
"figma:build": "BABEL_ENV=figma build-figma-plugin",
```

```js
env: {
        figma: {
            only: ['./packages/figma'],
        },
    },
```

**Comment by reintroducing** [comment]
Considering I've solved my issue and this is a very specific setup to my use case, I'm going to go ahead and close this out.
